'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronRight, Code2, FileDiff, FlaskConical, Gauge, GitBranch, Info, Layers3, MessageSquare, Play, ShieldCheck, Sparkles, Terminal, TrendingUp, X } from 'lucide-react'
import { ShellLayout } from '@/components/shell/shell-layout'

type Stage = 'Ideation' | 'Coding' | 'Backtesting' | 'Paper Trading' | 'Live Eligible' | 'Live' | 'Deprecated'
type Strategy = { name: string; instrument: 'Equity' | 'F&O'; stage: Stage; age: string; pnl: number; summary: string; legs?: { side: string; strike: string; expiry: string; qty: string }[] }

const stages: Stage[] = ['Ideation', 'Coding', 'Backtesting', 'Paper Trading', 'Live Eligible', 'Live', 'Deprecated']
const strategies: Strategy[] = [
  { name: 'NIFTY-Weekly-IronCondor', instrument: 'F&O', stage: 'Live Eligible', age: '3d', pnl: 18, summary: 'Sells a defined-risk weekly iron condor around the opening implied-volatility range, then hedges when the spot exits the expected move.', legs: [{ side: 'SELL', strike: '22,800 CE', expiry: '27 Jun 2025', qty: '50' }, { side: 'BUY', strike: '22,950 CE', expiry: '27 Jun 2025', qty: '50' }, { side: 'SELL', strike: '22,400 PE', expiry: '27 Jun 2025', qty: '50' }, { side: 'BUY', strike: '22,250 PE', expiry: '27 Jun 2025', qty: '50' }] },
  { name: 'BANKNIFTY-ORB-Breakout', instrument: 'F&O', stage: 'Paper Trading', age: '6d', pnl: 12, summary: 'Enters a momentum trade when Bank Nifty breaks the first 15-minute range with volume confirmation and exits on a trailing ATR stop.' },
  { name: 'RELIANCE-MeanReversion-v2', instrument: 'Equity', stage: 'Live', age: '21d', pnl: 26, summary: 'Fades two-standard-deviation deviations from the anchored VWAP while respecting a sector-relative strength filter.' },
  { name: 'TCS-Earnings-Drift', instrument: 'Equity', stage: 'Backtesting', age: '2d', pnl: 8, summary: 'Captures post-earnings drift using overnight gap quality, analyst revision breadth, and a five-day holding window.' },
  { name: 'FINNIFTY-Calendar-Spread', instrument: 'F&O', stage: 'Coding', age: '1d', pnl: 0, summary: 'Builds a calendar spread when front-month skew dislocates from the next expiry and manages vega exposure intraday.' },
  { name: 'HDFCBANK-Pairs-v1', instrument: 'Equity', stage: 'Ideation', age: '4h', pnl: 0, summary: 'Explores a cointegrated pair between HDFCBANK and ICICIBANK with beta-neutral position sizing.' },
  { name: 'NIFTY-Momentum-v0', instrument: 'F&O', stage: 'Deprecated', age: '48d', pnl: -4, summary: 'Archived after live/backtest divergence breached the risk policy for three consecutive sessions.' },
]

const code = `def generate_signal(ctx):\n    ema_fast = ctx.ema("close", 20)\n    ema_slow = ctx.ema("close", 50)\n    rsi = ctx.rsi("close", 14)\n\n    if ema_fast.crosses_above(ema_slow) and rsi > 55:\n        return Signal.long(\n            symbol=ctx.symbol,\n            risk_budget=0.012,\n            stop=ATR(14) * 2.1,\n        )\n\n    return Signal.flat()`

function Sparkline({ positive }: { positive: boolean }) { return <span className={`strategy-spark ${positive ? 'positive' : 'negative'}`}><i /><i /><i /><i /><i /><i /></span> }
function Badge({ children, tone = 'cyan' }: { children: React.ReactNode; tone?: string }) { return <span className={`strategy-badge tone-${tone}`}>{children}</span> }

function Review({ strategy, onBack }: { strategy: Strategy; onBack: () => void }) {
  const [tab, setTab] = useState('Logic')
  const [feedback, setFeedback] = useState('')
  const [reviewed, setReviewed] = useState(false)
  const checks = [{ label: 'Trade count', current: 42, threshold: 30, suffix: 'trades' }, { label: 'Elapsed days', current: 24, threshold: 21, suffix: 'days' }, { label: 'Clean Shadow Mode streak', current: 13, threshold: 10, suffix: 'days' }, { label: 'Live / backtest win-rate divergence', current: 12, threshold: 20, suffix: 'pp', inverse: true }]
  return <div className="mx-auto w-full max-w-[1700px]">
    <button onClick={onBack} className="mb-4 flex items-center gap-2 text-xs text-cyan-200 transition hover:text-white"><ArrowLeft className="size-4" /> Back to lifecycle board</button>
    <div className="strategy-review-hero"><div><div className="flex flex-wrap items-center gap-2"><Badge>{strategy.instrument}</Badge><Badge tone="green">{strategy.stage}</Badge><span className="font-mono text-[10px] text-slate-500">STRATEGY ID · {strategy.name.toUpperCase()}</span></div><h1 className="mt-3 text-2xl font-semibold tracking-tight text-white">{strategy.name}</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">{strategy.summary}</p></div><div className="strategy-review-score"><span>READINESS</span><strong>86%</strong><small>4 / 4 checks</small></div></div>
    <div className="strategy-tabs">{['Logic', 'Code', 'Code Diff', ...(strategy.instrument === 'F&O' ? ['Options Legs'] : []), 'Go-Live Readiness'].map(item => <button key={item} onClick={() => setTab(item)} className={tab === item ? 'active' : ''}>{item === 'Code' ? <Code2 className="size-3.5" /> : item === 'Code Diff' ? <FileDiff className="size-3.5" /> : item === 'Go-Live Readiness' ? <Gauge className="size-3.5" /> : null}{item}</button>)}</div>
    <div className="strategy-review-panel">
      {tab === 'Logic' && <div className="review-content"><div className="review-icon"><Sparkles className="size-5" /></div><p className="eyebrow">GENERATED LOGIC SUMMARY</p><h2>Momentum confirmation with volatility-aware exits</h2><p>Enters long when 20-EMA crosses above 50-EMA with RSI &gt; 55, exits on an ATR-based trailing stop. The strategy avoids entries during the first 15 minutes and reduces risk when India VIX expands beyond its rolling 20-day percentile.</p><div className="logic-grid"><div><span>ENTRY SIGNAL</span><strong>EMA cross + RSI &gt; 55</strong></div><div><span>RISK MODEL</span><strong>1.2% per trade</strong></div><div><span>EXIT MODEL</span><strong>ATR × 2.1 trailing stop</strong></div></div></div>}
      {tab === 'Code' && <div className="review-content"><div className="code-toolbar"><span><Terminal className="size-4 text-cyan-300" /> generated_strategy.py</span><Badge tone="green">READ ONLY</Badge></div><pre className="strategy-code"><code>{code}</code></pre><div className="feedback-box"><label htmlFor="feedback">Suggest Improvement</label><div className="flex gap-2"><textarea id="feedback" value={feedback} onChange={e => setFeedback(e.target.value)} placeholder="Ask the AI reviewer to improve risk controls, clarity, or execution logic..." /><button disabled={!feedback.trim()} onClick={() => setReviewed(true)}><MessageSquare className="size-4" /> Submit</button></div>{reviewed && <div className="verdict"><Sparkles className="size-4 text-violet-300" /><div><strong>AI Review Verdict · Consider</strong><p>Good signal hygiene. Add a maximum holding-period guard and cap correlated positions before promoting to live.</p></div></div>}</div></div>}
      {tab === 'Code Diff' && <div className="review-content"><div className="diff-header"><span>v2.4 current</span><span>v2.3 previous</span></div><div className="diff-code"><pre><span className="diff-remove">- stop = ATR(14) * 1.8</span>{'\n'}<span className="diff-add">+ stop = ATR(14) * 2.1</span>{'\n'}<span className="diff-add">+ risk_budget = min(risk_budget, 0.012)</span>{'\n'}<span>  return Signal.long(symbol=ctx.symbol)</span></pre></div></div>}
      {tab === 'Options Legs' && <div className="review-content"><div className="flex items-center justify-between"><div><p className="eyebrow">DEFINED RISK STRUCTURE</p><h2 className="mt-2">Options legs</h2></div><Badge tone="green"><ShieldCheck className="size-3" /> NAKED OPTIONS SCAN: PASS</Badge></div><div className="overflow-x-auto"><table className="strategy-table"><thead><tr><th>Side</th><th>Strike</th><th>Expiry</th><th>Quantity</th></tr></thead><tbody>{strategy.legs?.map(leg => <tr key={leg.strike}><td><Badge tone={leg.side === 'BUY' ? 'green' : 'amber'}>{leg.side}</Badge></td><td>{leg.strike}</td><td>{leg.expiry}</td><td>{leg.qty}</td></tr>)}</tbody></table></div></div>}
      {tab === 'Go-Live Readiness' && <div className="review-content"><div className="readiness-banner"><Check className="size-5" /><div><strong>Eligible for live promotion</strong><p>All policy gates are currently satisfied.</p></div></div><div className="readiness-list">{checks.map(check => { const progress = Math.min(check.current / check.threshold * 100, 100); const pass = check.inverse ? check.current <= check.threshold : check.current >= check.threshold; return <div className="readiness-row" key={check.label}><div className="flex items-center justify-between gap-3"><span>{check.label}</span><strong className={pass ? 'pass' : ''}>{check.current}{check.suffix === 'pp' ? 'pp' : ` ${check.suffix}`} / {check.threshold}{check.suffix === 'pp' ? 'pp' : ` ${check.suffix}`}</strong></div><div className="progress-track mt-2"><span style={{ width: `${progress}%` }} /></div><small>{pass ? 'PASS · policy threshold met' : 'PENDING · needs more evidence'}</small></div>})}</div></div>}
    </div>
  </div>
}

export default function StrategiesPage() {
  const [selected, setSelected] = useState<Strategy | null>(null)
  const grouped = useMemo(() => Object.fromEntries(stages.map(stage => [stage, strategies.filter(item => item.stage === stage)])) as Record<Stage, Strategy[]>, [])
  if (selected) return <ShellLayout><Review strategy={selected} onBack={() => setSelected(null)} /></ShellLayout>
  return <ShellLayout><div className="mx-auto w-full max-w-[1700px]"><div className="strategy-page-header"><div><p className="eyebrow">TRADINGOS // STRATEGY CONTROL PLANE</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-white">Strategy lifecycle</h1><p className="mt-2 text-sm text-slate-400">From generated hypothesis to controlled live capital. Select a strategy to open its review workspace.</p></div><div className="strategy-header-stats"><div><strong>{strategies.length}</strong><span>TRACKED</span></div><div><strong>03</strong><span>IN FLIGHT</span></div><div><strong className="text-emerald-300">01</strong><span>LIVE</span></div></div></div><div className="strategy-board">{stages.map((stage, index) => <section className="strategy-column" key={stage}><div className="strategy-column-title"><div><span className="stage-index">0{index + 1}</span><h2>{stage}</h2></div><span className="stage-count">{grouped[stage].length}</span></div><div className="strategy-cards">{grouped[stage].map(item => <button className="strategy-card" key={item.name} onClick={() => setSelected(item)}><div className="flex items-start justify-between gap-2"><Badge tone={item.instrument === 'F&O' ? 'violet' : 'cyan'}>{item.instrument}</Badge><span className="font-mono text-[10px] text-slate-500">{item.age}</span></div><h3>{item.name}</h3><div className="flex items-center justify-between gap-2"><span className={`flex items-center gap-1 text-[10px] ${item.pnl >= 0 ? 'text-emerald-300' : 'text-rose-300'}`}><TrendingUp className="size-3" /> {item.pnl ? `+${item.pnl}% paper P&L` : 'awaiting signal'}</span>{item.pnl !== 0 && <Sparkline positive={item.pnl > 0} />}</div><div className="mt-3 flex items-center justify-between border-t border-white/8 pt-2 text-[10px] text-slate-500"><span>REVIEW WORKSPACE</span><ChevronRight className="size-3.5 text-cyan-300" /></div></button>)}</div></section>)}</div></div></ShellLayout>
}
