'use client'

import { useMemo, useState } from 'react'
import { AlertTriangle, Bot, Check, GripVertical, LockKeyhole, Pause, Plus, RotateCcw, Save, Search, ShieldCheck, SlidersHorizontal, Sparkles, X, Zap } from 'lucide-react'
import { ShellLayout } from '@/components/shell/shell-layout'

type AgentStatus = 'active' | 'degraded' | 'disabled' | 'executing'
type Department = 'Executive' | 'Market Intelligence' | 'Research' | 'Quant' | 'Risk & Governance' | 'Portfolio' | 'Operations'

type Agent = { id: string; name: string; department: Department; status: AgentStatus; icon: string; description: string; cannotDisable?: boolean; skills: string[] }

const departments: { name: Department; color: string; short: string }[] = [
  { name: 'Executive', color: '#c084fc', short: 'EXE' }, { name: 'Market Intelligence', color: '#38bdf8', short: 'MKT' }, { name: 'Research', color: '#818cf8', short: 'RES' }, { name: 'Quant', color: '#22d3ee', short: 'QNT' }, { name: 'Risk & Governance', color: '#fb7185', short: 'RSK' }, { name: 'Portfolio', color: '#34d399', short: 'PFM' }, { name: 'Operations', color: '#fbbf24', short: 'OPS' },
]

const agents: Agent[] = [
  { id: 'ceo', name: 'CEO Agent', department: 'Executive', status: 'active', icon: '◈', description: 'Orchestrates organization-wide reasoning, priorities, and approvals.', skills: ['Orchestration', 'Decisioning', 'Memory'] },
  { id: 'ceo-chat', name: 'CEO Chat Interface', department: 'Executive', status: 'active', icon: '◉', description: 'Human-facing conversational control plane.', skills: ['Conversation', 'Tool Use'] },
  { id: 'market', name: 'Market Analyst', department: 'Market Intelligence', status: 'active', icon: '⌁', description: 'Scans market structure and cross-asset signals.', skills: ['Market Data', 'Technical Analysis'] },
  { id: 'news', name: 'News Agent', department: 'Market Intelligence', status: 'executing', icon: '▤', description: 'Ingests and summarizes live news catalysts.', skills: ['Web Research', 'Summarization'] },
  { id: 'sentiment', name: 'Sentiment Agent', department: 'Market Intelligence', status: 'idle' as AgentStatus, icon: '◌', description: 'Scores market sentiment across sources.', skills: ['NLP', 'Signal Scoring'] },
  { id: 'strategy', name: 'Strategy Generator', department: 'Research', status: 'active', icon: '✦', description: 'Generates and stress-tests systematic strategy ideas.', skills: ['Strategy Design', 'Backtesting', 'Python'] },
  { id: 'options', name: 'Options Strategy Agent', department: 'Research', status: 'degraded', icon: '◇', description: 'Constructs defined-risk options structures.', skills: ['Options', 'Greeks'] },
  { id: 'python', name: 'Python Code Generator', department: 'Quant', status: 'active', icon: '⌘', description: 'Writes reproducible research and execution code.', skills: ['Python', 'Codegen'] },
  { id: 'validator', name: 'Python Validator', department: 'Quant', status: 'active', icon: '✓', description: 'Validates generated code and data assumptions.', skills: ['Testing', 'Python'] },
  { id: 'backtest', name: 'Backtesting Agent', department: 'Quant', status: 'executing', icon: '◫', description: 'Runs historical simulations against strategy candidates.', skills: ['Backtesting', 'Statistics'] },
  { id: 'optimization', name: 'Optimization Agent', department: 'Quant', status: 'active', icon: '↗', description: 'Optimizes parameters within governance bounds.', skills: ['Optimization', 'Numerical'] },
  { id: 'evaluator', name: 'Evaluator', department: 'Quant', status: 'active', icon: '⊙', description: 'Ranks experiment outcomes and confidence.', skills: ['Evaluation', 'Reporting'] },
  { id: 'risk', name: 'Risk Manager', department: 'Risk & Governance', status: 'active', icon: '△', description: 'Maintains the risk perimeter and position limits.', cannotDisable: true, skills: ['Risk Policy', 'Exposure', 'Approvals'] },
  { id: 'compliance', name: 'Compliance Agent', department: 'Risk & Governance', status: 'active', icon: '▣', description: 'Checks strategies against compliance policies.', skills: ['Compliance', 'Policy'] },
  { id: 'audit', name: 'Audit Agent', department: 'Risk & Governance', status: 'active', icon: '⊞', description: 'Seals immutable evidence for every decision.', cannotDisable: true, skills: ['Audit Trail', 'Evidence'] },
  { id: 'deployment', name: 'Deployment Agent', department: 'Risk & Governance', status: 'disabled', icon: '⇧', description: 'Promotes approved strategies between environments.', skills: ['Deployment', 'Release'] },
  { id: 'portfolio', name: 'Portfolio Manager Agent', department: 'Portfolio', status: 'active', icon: '◒', description: 'Coordinates allocation proposals and portfolio state.', skills: ['Allocation', 'Portfolio'] },
  { id: 'memory', name: 'Memory Agent', department: 'Operations', status: 'active', icon: '▥', description: 'Maintains durable organizational memory.', skills: ['Memory', 'Retrieval'] },
  { id: 'ingestion', name: 'Data Ingestion Agent', department: 'Operations', status: 'active', icon: '⇣', description: 'Keeps market and reference data flowing.', skills: ['Pipelines', 'Data Quality'] },
  { id: 'scheduler', name: 'Scheduler Agent', department: 'Operations', status: 'active', icon: '◷', description: 'Coordinates recurring jobs and heartbeats.', skills: ['Scheduling', 'Workflows'] },
  { id: 'notification', name: 'Notification Agent', department: 'Operations', status: 'active', icon: '⌁', description: 'Routes alerts to the right human channel.', skills: ['Alerts', 'Routing'] },
  { id: 'skills', name: 'Skill Registry Manager', department: 'Operations', status: 'active', icon: '✺', description: 'Manages the approved capability registry.', skills: ['Skills', 'Permissions'] },
  { id: 'execution', name: 'Execution Agent', department: 'Operations', status: 'degraded', icon: '⇄', description: 'Prepares paper execution instructions.', skills: ['Execution', 'Order Prep'] },
  { id: 'paper', name: 'Paper Trading Engine', department: 'Operations', status: 'active', icon: '▰', description: 'Simulates fills and maintains paper ledger.', skills: ['Paper Trading', 'Ledger'] },
]

const providers = ['OpenAI / GPT-5', 'Anthropic / Claude Sonnet', 'Google / Gemini Pro', 'xAI / Grok', 'Mistral / Large', 'DeepSeek / Reasoner', 'Local / Llama 4']
const tabs = ['Identity', 'Model & Routing', 'Prompt Versions', 'Skills', 'Heartbeat', 'Enable / Disable']

function StatusDot({ status }: { status: AgentStatus }) { return <span className={`agent-status-dot status-${status}`} title={status} /> }
function Node({ agent, onClick, selected }: { agent: Agent; onClick: () => void; selected: boolean }) { return <button onClick={onClick} className={`fleet-node ${selected ? 'fleet-node-selected' : ''}`} style={{ '--dept-color': departments.find((d) => d.name === agent.department)?.color } as React.CSSProperties}><span className="node-icon">{agent.icon}</span><span className="min-w-0 text-left"><strong>{agent.name}</strong><small><StatusDot status={agent.status} />{agent.status}</small></span></button> }

function AgentWorkspace({ agent, onClose }: { agent: Agent; onClose: () => void }) {
  const [tab, setTab] = useState('Identity')
  const [name, setName] = useState(agent.name)
  const [enabled, setEnabled] = useState(agent.status !== 'disabled')
  const [heartbeat, setHeartbeat] = useState(true)
  const [interval, setInterval] = useState(15)
  const dept = departments.find((d) => d.name === agent.department)!
  return <aside className="fleet-workspace"><div className="workspace-header"><div><p className="eyebrow">AGENT WORKSPACE</p><h2>{agent.name}</h2><p className="workspace-sub"><StatusDot status={agent.status} /> {agent.department} · v2.4.1</p></div><button className="icon-button" onClick={onClose} aria-label="Close workspace"><X /></button></div><div className="workspace-tabs">{tabs.map((item) => <button key={item} className={tab === item ? 'workspace-tab-active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div><div className="workspace-body">
    {tab === 'Identity' && <div className="tab-stack"><div className="agent-preview" style={{ '--dept-color': dept.color } as React.CSSProperties}><span className="preview-orb">{agent.icon}</span><div><p className="eyebrow">LIVE PREVIEW</p><strong>{name || 'Unnamed Agent'}</strong><small>{agent.department} · {agent.status}</small></div><Sparkles className="ml-auto size-4" /></div><label>Display name<input value={name} onChange={(e) => setName(e.target.value)} /></label><div className="two-col"><label>Emoji / icon<input defaultValue={agent.icon} /></label><label>Voice / TTS<select defaultValue="No voice profile"><option>No voice profile</option><option>Calm operator</option><option>Executive brief</option></select></label></div><label>Accent theme<div className="color-swatches">{departments.map((d) => <button key={d.name} aria-label={d.name} style={{ background: d.color }} className={d.name === agent.department ? 'swatch-selected' : ''} />)}</div></label><button className="primary-action"><Save /> Save identity</button></div>}
    {tab === 'Model & Routing' && <div className="tab-stack"><div className="segmented"><button className="segment-active">AUTO <small>Global fallback chain</small></button><button>CUSTOM <small>Pin provider/model</small></button></div><div className="section-label"><span>GLOBAL PROVIDER ORDER</span><span className="live-pill">7 ONLINE</span></div><p className="muted-copy">The agent retries down this chain when a provider is unavailable.</p>{providers.map((provider, index) => <div className="provider-row" key={provider}><GripVertical className="size-4 text-muted-foreground" /><span className="provider-rank">0{index + 1}</span><span>{provider}</span><Check className="ml-auto size-4 text-emerald-300" /></div>)}</div>}
    {tab === 'Prompt Versions' && <div className="tab-stack"><div className="section-label"><span>VERSION HISTORY</span><button className="text-button">Compare versions</button></div>{['v2.4.1 · active', 'v2.4.0 · 2 days ago', 'v2.3.0 · 1 week ago'].map((version, index) => <div className={`version-row ${index === 0 ? 'version-active' : ''}`} key={version}><div><strong>{version}</strong><small>{index === 0 ? 'Production prompt · 1,842 tokens' : 'Archived · reviewed by System Administrator'}</small></div>{index > 0 && <button className="outline-action">Activate</button>}</div>)}<div className="diff-box"><p className="eyebrow">DIFF PREVIEW · v2.4.0 → v2.4.1</p><code><span className="diff-remove">- prioritize raw signal velocity</span><br /><span className="diff-add">+ prioritize risk-adjusted signal quality</span></code></div><button className="primary-action"><ShieldCheck /> Review activation</button></div>}
    {tab === 'Skills' && <div className="tab-stack"><div className="section-label"><span>GRANTED SKILLS · {agent.skills.length}</span><button className="text-button"><Plus /> Add skill</button></div><div className="skill-grid">{agent.skills.map((skill) => <span className="skill-chip" key={skill}>{skill}<X /></span>)}{['Market Context', 'Report Builder'].map((skill) => <span className="skill-chip skill-muted" key={skill}>{skill}<Plus /></span>)}</div><div className="callout"><LockKeyhole /><span>Skills are governed by role policy and require an audit event to revoke.</span></div></div>}
    {tab === 'Heartbeat' && <div className="tab-stack"><div className="setting-row"><div><strong>Heartbeat observer</strong><small>Periodic health and signal check</small></div><button className={`toggle ${heartbeat ? 'toggle-on' : ''}`} onClick={() => setHeartbeat(!heartbeat)} aria-label="Toggle heartbeat"><span /></button></div><label>Interval <span className="range-value">{interval} min</span><input className="range-input" type="range" min="5" max="30" value={interval} onChange={(e) => setInterval(Number(e.target.value))} /></label><div className="callout callout-cyan"><Zap /><span>Heartbeat can only observe and raise alerts — it cannot place, modify, or cancel any order.</span></div></div>}
    {tab === 'Enable / Disable' && <div className="tab-stack"><div className="danger-banner"><AlertTriangle /><div><strong>{enabled ? 'Agent is enabled' : 'Agent is disabled'}</strong><small>Changes are recorded in the immutable audit trail.</small></div></div><div className="setting-row"><div><strong>Operational status</strong><small>{agent.cannotDisable ? 'Protected system agent' : 'Allow this agent to run tasks'}</small></div><button disabled={agent.cannotDisable} className={`toggle ${enabled ? 'toggle-on' : ''}`} onClick={() => setEnabled(!enabled)} aria-label="Toggle agent status"><span /></button></div>{agent.cannotDisable ? <div className="callout"><LockKeyhole /><span>Cannot be disabled. {agent.name} is required for governance and safety of the trading system.</span></div> : !enabled && <label>Reason required<textarea placeholder="Why is this agent being disabled?" /></label>}</div>}
  </div></aside>
}

export default function AgentFleetPage() {
  const [selected, setSelected] = useState<Agent | null>(agents[0])
  const [query, setQuery] = useState('')
  const [zoom, setZoom] = useState(1)
  const filtered = useMemo(() => agents.filter((agent) => agent.name.toLowerCase().includes(query.toLowerCase())), [query])
  return <ShellLayout><div className="mx-auto flex w-full max-w-[1800px] flex-col gap-5"><header className="fleet-page-header"><div><p className="eyebrow">TRADINGOS // AGENT FLEET</p><h1>Organization intelligence map</h1><p>24 specialized agents · one governed execution layer</p></div><div className="fleet-header-actions"><div className="search-box"><Search /><input placeholder="Find an agent" value={query} onChange={(e) => setQuery(e.target.value)} /></div><button className="outline-action"><SlidersHorizontal /> Filter</button></div></header><div className="fleet-layout"><section className="fleet-canvas"><div className="canvas-toolbar"><span className="live-pill"><span className="status-dot" /> SYSTEM ONLINE</span><div><button onClick={() => setZoom(Math.max(.75, zoom - .1))}>−</button><span>{Math.round(zoom * 100)}%</span><button onClick={() => setZoom(Math.min(1.25, zoom + .1))}>+</button><button onClick={() => setZoom(1)}><RotateCcw /></button></div></div><div className="tree-viewport"><div className="tree-content" style={{ transform: `scale(${zoom})` }}><div className="tree-root"><Node agent={agents[0]} selected={selected?.id === 'ceo'} onClick={() => setSelected(agents[0])} /></div><div className="tree-connector vertical" /><div className="department-row">{departments.map((department) => <div className="department-column" key={department.name}><div className="connector-line" style={{ background: department.color }} /><div className="department-label" style={{ '--dept-color': department.color } as React.CSSProperties}><span>{department.short}</span>{department.name}</div><div className="agent-stack">{filtered.filter((a) => a.department === department.name && a.id !== 'ceo').map((agent) => <Node key={agent.id} agent={agent} selected={selected?.id === agent.id} onClick={() => setSelected(agent)} />)}</div></div>)}</div></div></div><div className="tree-legend"><span><StatusDot status="active" /> Active / idle</span><span><StatusDot status="executing" /> Executing</span><span><StatusDot status="degraded" /> Degraded</span><span><StatusDot status="disabled" /> Disabled</span></div></section>{selected && <AgentWorkspace key={selected.id} agent={selected} onClose={() => setSelected(null)} />}</div><div className="fleet-footer"><span><Bot /> {agents.length} agents registered</span><span><ShieldCheck /> Governance policy enforced</span><span><Pause /> Paper environment only</span></div></div></ShellLayout>
}

export { agents }
