'use client'

import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowUp, Check, ChevronLeft, ChevronRight, Clock3, Download, History, LockKeyhole, Search, ShieldAlert, Timer, X, Zap } from 'lucide-react'
import { ShellLayout } from '@/components/shell/shell-layout'

type Order = { time: string; symbol: string; side: 'BUY' | 'SELL'; qty: number; price: string; status: string; source: string; latency: number; mode: 'PAPER' | 'LIVE' }
const orders: Order[] = [
  { time:'09:18:42', symbol:'NIFTY 24 JUN 24500 CE', side:'BUY', qty:50, price:'₹182.40', status:'FILLED', source:'Momentum Scout', latency:24, mode:'PAPER' },
  { time:'09:21:08', symbol:'RELIANCE', side:'SELL', qty:120, price:'₹2,941.80', status:'FILLED', source:'Mean Reversion', latency:31, mode:'LIVE' },
  { time:'09:27:15', symbol:'BANKNIFTY FUT', side:'BUY', qty:15, price:'₹51,220.00', status:'OPEN', source:'ORB Breakout', latency:48, mode:'PAPER' },
  { time:'09:34:51', symbol:'HDFCBANK', side:'BUY', qty:75, price:'₹1,742.25', status:'PARTIAL', source:'Alpha Engine', latency:67, mode:'LIVE' },
  { time:'09:46:23', symbol:'TCS', side:'SELL', qty:40, price:'₹3,884.10', status:'CANCELLED', source:'Earnings Drift', latency:39, mode:'PAPER' },
  { time:'10:02:17', symbol:'INFY', side:'BUY', qty:160, price:'₹1,592.60', status:'FILLED', source:'Mean Reversion', latency:28, mode:'PAPER' },
  { time:'10:18:04', symbol:'NIFTY FUT', side:'SELL', qty:25, price:'₹24,486.50', status:'REJECTED', source:'Risk Sentinel', latency:92, mode:'LIVE' },
  { time:'10:31:46', symbol:'ICICIBANK', side:'BUY', qty:90, price:'₹1,284.90', status:'FILLED', source:'Momentum Scout', latency:22, mode:'LIVE' },
]
const intents = [
  ['LI-0082','RELIANCE','SELL · 120 qty','APPROVED','09:20:54','Mean Reversion'], ['LI-0081','NIFTY FUT','SELL · 25 qty','REJECTED','10:17:02','Risk Sentinel'], ['LI-0080','HDFCBANK','BUY · 75 qty','PENDING','00:28','Alpha Engine'], ['LI-0079','TCS','SELL · 40 qty','EXPIRED','08:46:11','Earnings Drift'], ['LI-0078','ICICIBANK','BUY · 90 qty','APPROVED','10:30:41','Momentum Scout'],
]
const strategyPnl = [['Momentum Scout','+₹42,680',72],['Mean Reversion','+₹28,340',48],['ORB Breakout','+₹18,920',34],['Earnings Drift','−₹5,680',10]]
function Panel({ title, eyebrow, children }: { title:string; eyebrow?:string; children:React.ReactNode }) { return <section className="orders-panel"><div className="orders-panel-head"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div></div>{children}</section> }

export default function OrdersPage() {
  const [mode, setMode] = useState('BOTH'), [status, setStatus] = useState('ALL'), [query, setQuery] = useState(''), [tab, setTab] = useState('orders'), [page, setPage] = useState(1), [live, setLive] = useState(false), [confirm, setConfirm] = useState(false), [symbol, setSymbol] = useState('RELIANCE'), [side, setSide] = useState('BUY'), [qty, setQty] = useState('50'), [orderType, setOrderType] = useState('MARKET')
  const filtered = useMemo(() => orders.filter(o => (mode === 'BOTH' || o.mode === mode) && (status === 'ALL' || o.status === status) && o.symbol.toLowerCase().includes(query.toLowerCase())), [mode,status,query])
  const submitOrder = () => { if (live) setConfirm(true); else setLive(false) }
  return <ShellLayout><main className="orders-page mx-auto w-full max-w-[1700px] pb-10">
    <header className="orders-header"><div><p className="eyebrow">TRADINGOS // EXECUTION CONTROL</p><h1>Orders &amp; Trades</h1><p>Unified paper and live execution ledger · NSE / BSE gateways synchronized</p></div><button className="orders-export"><Download className="size-4" /> Export CSV</button></header>
    <section className="orders-summary"><div className="summary-pnl"><p className="eyebrow">TODAY&apos;S P&amp;L BY STRATEGY</p>{strategyPnl.map(([name,value,width]) => <div className="pnl-row" key={name}><span>{name}</span><strong className={String(value).startsWith('−')?'loss':'gain'}>{value}</strong><i><b style={{width:`${width}%`}} /></i></div>)}</div><div className="summary-stat"><span>OPEN POSITIONS</span><strong>07</strong><small>4 paper · 3 live</small></div><div className="summary-stat"><span>LATENCY P50</span><strong>31ms</strong><small className="gain">Within 50ms budget</small></div><div className="summary-stat"><span>LATENCY P95</span><strong className="warning-text">68ms</strong><small>+18ms over budget</small></div></section>
    <div className="orders-layout"><div className="orders-main"><div className="orders-tabs"><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Orders &amp; Trades <b>24</b></button><button className={tab==='intents'?'active':''} onClick={()=>setTab('intents')}>Live Order Intents <b className="amber-count">05</b></button></div>{tab==='orders' ? <Panel title="Execution ledger" eyebrow="PAPER + LIVE · NEWEST FIRST"><div className="orders-filters"><div className="filter-chips">{['BOTH','PAPER','LIVE'].map(x=><button className={mode===x?'active':''} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><select value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>FILLED</option><option>OPEN</option><option>PARTIAL</option><option>REJECTED</option><option>CANCELLED</option></select><label className="symbol-search"><Search className="size-3" /><input placeholder="Search symbol..." value={query} onChange={e=>setQuery(e.target.value)} /></label></div><div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>TIME</th><th>SYMBOL</th><th>SIDE</th><th>QTY</th><th>PRICE</th><th>STATUS</th><th>STRATEGY SOURCE</th><th>LATENCY</th></tr></thead><tbody>{filtered.slice((page-1)*5,page*5).map(o=><tr key={o.time+o.symbol}><td className="mono">{o.time}<small>{o.mode}</small></td><td>{o.symbol}</td><td><span className={o.side==='BUY'?'buy-badge':'sell-badge'}>{o.side==='BUY'?<ArrowUp className="size-3"/>:<ArrowDown className="size-3"/>}{o.side}</span></td><td>{o.qty}</td><td className="mono">{o.price}</td><td><span className={`status-badge status-${o.status.toLowerCase()}`}>{o.status}</span></td><td className="source-cell">{o.source}</td><td className={o.latency>50?'warning-text':'gain'}>{o.latency}ms</td></tr>)}</tbody></table></div><div className="orders-footer"><span>Showing {(page-1)*5+1}–{Math.min(page*5,filtered.length)} of {filtered.length} executions</span><div><button disabled={page===1} onClick={()=>setPage(1)}><ChevronLeft className="size-3"/></button><button disabled={page>=2} onClick={()=>setPage(2)}><ChevronRight className="size-3"/></button></div></div></Panel> : <Panel title="Live Order Intents" eyebrow="FULL HISTORY · HUMAN SIGN-OFF TRAIL"><div className="intent-history">{intents.map(([id,sym,detail,outcome,when,source])=><div className="intent-row" key={id}><div className={`intent-ring ring-${outcome.toLowerCase()}`}><Timer className="size-4" /></div><div className="intent-info"><strong>{sym}</strong><span>{detail} · {source}</span><small>{id} · {when}</small></div><span className={`outcome outcome-${outcome.toLowerCase()}`}>{outcome==='APPROVED'?<Check className="size-3"/>:outcome==='REJECTED'||outcome==='EXPIRED'?<X className="size-3"/>:<Clock3 className="size-3"/>}{outcome}</span></div>)}</div></Panel>}</div>
    <aside className="orders-side"><Panel title="Manual order entry" eyebrow="HUMAN-TRIGGERED PATH"><div className="mode-toggle"><button className={!live?'selected-paper':''} onClick={()=>setLive(false)}>PAPER<small>Safe simulation</small></button><button className={live?'selected-live':''} onClick={()=>setLive(true)}>LIVE<small>Requires confirmation</small></button></div>{live&&<div className="live-warning"><ShieldAlert className="size-4"/><span><strong>LIVE ORDER</strong><small>This routes to a broker gateway and changes real exposure.</small></span></div>}<label className="order-field">SYMBOL<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/><small>Suggestions: RELIANCE · NIFTY FUT · BANKNIFTY</small></label><div className="field-grid"><label className="order-field">SIDE<select value={side} onChange={e=>setSide(e.target.value)}><option>BUY</option><option>SELL</option></select></label><label className="order-field">QUANTITY<input type="number" value={qty} onChange={e=>setQty(e.target.value)}/></label></div><label className="order-field">ORDER TYPE<select value={orderType} onChange={e=>setOrderType(e.target.value)}><option>MARKET</option><option>LIMIT</option><option>STOP</option></select></label><button className={live?'submit-live':'submit-paper'} onClick={submitOrder}>{live?<><LockKeyhole className="size-4"/>Review LIVE order</>:<><Zap className="size-4"/>Place PAPER order</>}</button></Panel><Panel title="Gateway health" eyebrow="EXECUTION INFRA"><div className="gateway-row"><span className="gateway-dot"/> NSE Gateway <b>18ms</b></div><div className="gateway-row"><span className="gateway-dot"/> BSE Gateway <b>24ms</b></div><div className="gateway-row"><span className="gateway-dot gateway-warn"/> Broker session <b>Re-auth in 42m</b></div></Panel></aside></div>
    {confirm&&<div className="confirm-backdrop"><div className="confirm-modal"><button className="modal-close" onClick={()=>setConfirm(false)}><X className="size-4"/></button><ShieldAlert className="modal-icon"/><p className="eyebrow">FINAL LIVE ORDER CONFIRMATION</p><h2>{side} {qty} {symbol}</h2><p>This order will be routed to the live broker gateway at market price. Type the symbol below to confirm deliberate intent.</p><input autoFocus placeholder={`Type ${symbol} to confirm`} onChange={e=>{if(e.target.value.toUpperCase()===symbol) setConfirm(false)}}/><button className="submit-live" onClick={()=>setConfirm(false)}>Confirm and route LIVE order</button></div></div>}
  </main></ShellLayout>
}
export { orders }
