"""phase 10 market data tables

Revision ID: 0629b6f53022
Revises: aa300ec2e171
Create Date: 2026-09-17 05:39:15.480867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0629b6f53022'
down_revision: Union[str, None] = 'aa300ec2e171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('dividend','split','bonus','rights')", name='ck_corporate_actions_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'action_type', 'ex_date', name='uq_corporate_actions_symbol_type_exdate')
    )
    op.create_index(op.f('ix_corporate_actions_symbol'), 'corporate_actions', ['symbol'], unique=False)
    op.create_table('dataset_freshness_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('data_type', sa.String(length=16), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_type IN ('daily_ohlcv','intraday_ohlcv')", name='ck_dataset_freshness_records_data_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_type', 'data_date', name='uq_dataset_freshness_records_symbol_type_date')
    )
    op.create_index(op.f('ix_dataset_freshness_records_symbol'), 'dataset_freshness_records', ['symbol'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('instrument_type', sa.String(length=16), nullable=False),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=32), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('option_type', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("instrument_type IN ('equity','future','option','index')", name='ck_instruments_type'),
    sa.CheckConstraint("option_type IN ('CE','PE') OR option_type IS NULL", name='ck_instruments_option_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('market_data_provenance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('symbols_processed', sa.Integer(), nullable=False),
    sa.Column('rows_ingested', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pipeline IN ('incremental_daily','corporate_actions','instrument_master','intraday_minute','bhavcopy_fallback','catalog_refresh','data_lake_backup')", name='ck_market_data_provenance_pipeline'),
    sa.CheckConstraint("status IN ('success','partial','failed')", name='ck_market_data_provenance_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_provenance_pipeline'), 'market_data_provenance', ['pipeline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_provenance_pipeline'), table_name='market_data_provenance')
    op.drop_table('market_data_provenance')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_dataset_freshness_records_symbol'), table_name='dataset_freshness_records')
    op.drop_table('dataset_freshness_records')
    op.drop_index(op.f('ix_corporate_actions_symbol'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
