"""backtest and optimization run tables

Revision ID: 56d0bc776443
Revises: bda4770d5a76
Create Date: 2026-09-16 06:32:23.378965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d0bc776443'
down_revision: Union[str, None] = 'bda4770d5a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('friction_config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('daily_returns', sa.JSON(), nullable=True),
    sa.Column('trade_pnls', sa.JSON(), nullable=True),
    sa.Column('walk_forward_result', sa.JSON(), nullable=True),
    sa.Column('monte_carlo_result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','completed','refused_stale_data','failed')", name='ck_backtest_runs_status'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_strategy_version_id'), 'backtest_runs', ['strategy_version_id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('objective_metric', sa.String(length=32), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('best_params', sa.JSON(), nullable=True),
    sa.Column('best_value', sa.Float(), nullable=True),
    sa.Column('param_importance', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_strategy_version_id'), 'optimization_runs', ['strategy_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_runs_strategy_version_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_backtest_runs_strategy_version_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
