"""phase19_screener_and_reporting_tables

Revision ID: 68bf447ceabd
Revises: e9764af6c00d
Create Date: 2026-09-24 11:17:32.916424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bf447ceabd'
down_revision: Union[str, None] = 'e9764af6c00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.CheckConstraint("cadence IN ('weekly','monthly')", name='ck_investor_reports_cadence'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_reports_period_end'), 'investor_reports', ['period_end'], unique=False)
    op.create_table('operator_guidance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_review_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('trades_reviewed', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('pnl_scope', sa.String(length=24), nullable=False),
    sa.Column('commentary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('paper','live')", name='ck_trade_review_findings_mode'),
    sa.CheckConstraint("pnl_scope IN ('today','cumulative_to_date')", name='ck_trade_review_findings_pnl_scope'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_review_findings_review_date'), 'trade_review_findings', ['review_date'], unique=False)
    op.create_index(op.f('ix_trade_review_findings_strategy_id'), 'trade_review_findings', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_review_findings_strategy_id'), table_name='trade_review_findings')
    op.drop_index(op.f('ix_trade_review_findings_review_date'), table_name='trade_review_findings')
    op.drop_table('trade_review_findings')
    op.drop_table('operator_guidance')
    op.drop_index(op.f('ix_investor_reports_period_end'), table_name='investor_reports')
    op.drop_table('investor_reports')
    # ### end Alembic commands ###
