"""shadow_mode_run_table

Revision ID: 68e2bb4c29fe
Revises: afb82b5073aa
Create Date: 2026-09-16 11:49:52.596852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e2bb4c29fe'
down_revision: Union[str, None] = 'afb82b5073aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_mode_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_name', sa.String(length=32), nullable=False),
    sa.Column('has_sandbox', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_payload', sa.JSON(), nullable=False),
    sa.Column('broker_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('real_sandbox_dry_run','local_payload_only')", name='ck_shadow_mode_runs_confidence'),
    sa.CheckConstraint("side IN ('buy','sell')", name='ck_shadow_mode_runs_side'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_mode_runs_broker_name'), 'shadow_mode_runs', ['broker_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_mode_runs_broker_name'), table_name='shadow_mode_runs')
    op.drop_table('shadow_mode_runs')
    # ### end Alembic commands ###
