"""orchestration engine tables

Revision ID: 96fec4d5877a
Revises: d73dbd767857
Create Date: 2026-09-15 18:28:40.969764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fec4d5877a'
down_revision: Union[str, None] = 'd73dbd767857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('ui', 'schedule', 'chat', 'webhook', name='run_source'), nullable=False),
    sa.Column('run_type', sa.Enum('standard', 'rerun', name='run_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'planning', 'cannot_plan', 'running', 'paused', 'completed', 'failed', name='run_status'), nullable=False),
    sa.Column('source_run_id', sa.UUID(), nullable=True),
    sa.Column('failure_class', sa.Enum('transient', 'permanent', name='failure_class'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_run_id'], ['organization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('transition_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['organization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_run_id'), 'approval_requests', ['run_id'], unique=False)
    op.create_table('organizational_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['organization_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence')
    )
    op.create_index(op.f('ix_organizational_events_run_id'), 'organizational_events', ['run_id'], unique=False)
    op.create_table('organizational_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', name='plan_status'), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('planner_output', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['organization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizational_plans_run_id'), 'organizational_plans', ['run_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_key', sa.String(length=128), nullable=False),
    sa.Column('capability', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('produces_artefact_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ready', 'claimed', 'running', 'succeeded', 'failed', 'unsatisfiable', name='task_status'), nullable=False),
    sa.Column('claimed_by', sa.String(length=128), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('failure_class', sa.Enum('transient', 'permanent', name='failure_class'), nullable=True),
    sa.Column('stalled_flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['organizational_plans.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['organization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_run_id'), 'tasks', ['run_id'], unique=False)
    op.create_table('result_artefacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('artefact_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['organization_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_artefacts_run_id'), 'result_artefacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_result_artefacts_task_id'), 'result_artefacts', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.Column('artefact_type', sa.String(length=128), nullable=True),
    sa.Column('satisfied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id')
    )
    op.create_index(op.f('ix_task_dependencies_depends_on_task_id'), 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_table('organizational_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('decision_type', sa.String(length=128), nullable=False),
    sa.Column('subject_artefact_id', sa.UUID(), nullable=True),
    sa.Column('verdict', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['organization_runs.id'], ),
    sa.ForeignKeyConstraint(['subject_artefact_id'], ['result_artefacts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizational_decisions_run_id'), 'organizational_decisions', ['run_id'], unique=False)
    op.create_index(op.f('ix_organizational_decisions_subject_artefact_id'), 'organizational_decisions', ['subject_artefact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizational_decisions_subject_artefact_id'), table_name='organizational_decisions')
    op.drop_index(op.f('ix_organizational_decisions_run_id'), table_name='organizational_decisions')
    op.drop_table('organizational_decisions')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_task_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_result_artefacts_task_id'), table_name='result_artefacts')
    op.drop_index(op.f('ix_result_artefacts_run_id'), table_name='result_artefacts')
    op.drop_table('result_artefacts')
    op.drop_index(op.f('ix_tasks_run_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_organizational_plans_run_id'), table_name='organizational_plans')
    op.drop_table('organizational_plans')
    op.drop_index(op.f('ix_organizational_events_run_id'), table_name='organizational_events')
    op.drop_table('organizational_events')
    op.drop_index(op.f('ix_approval_requests_run_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('organization_runs')
    # ### end Alembic commands ###

    # Autogenerate's drop_table() calls above don't drop the native Postgres
    # ENUM types those columns created as a side effect (a recurring defect
    # class in this repo -- see Phase 0/1 migrations) -- without this, a
    # downgrade+upgrade round-trip fails with "type X already exists".
    # failure_class is shared by both organization_runs and tasks, so it's
    # dropped once, after both tables are gone.
    bind = op.get_bind()
    sa.Enum(name='run_source').drop(bind, checkfirst=True)
    sa.Enum(name='run_type').drop(bind, checkfirst=True)
    sa.Enum(name='run_status').drop(bind, checkfirst=True)
    sa.Enum(name='failure_class').drop(bind, checkfirst=True)
    sa.Enum(name='approval_status').drop(bind, checkfirst=True)
    sa.Enum(name='plan_status').drop(bind, checkfirst=True)
    sa.Enum(name='task_status').drop(bind, checkfirst=True)
