"""live_trading_tables

Revision ID: aa300ec2e171
Revises: 68e2bb4c29fe
Create Date: 2026-09-16 19:40:26.137104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa300ec2e171'
down_revision: Union[str, None] = '68e2bb4c29fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # Manually adjusted: live_order_intents.resulting_order_id and
    # orders.live_order_intent_id form a genuine circular FK pair (an
    # intent optionally points at the order it produced; an order always
    # points back at the intent that produced it). The model marks that
    # FK `use_alter=True` so SQLAlchemy excludes it from
    # live_order_intents' own CREATE TABLE -- correct, since `orders`
    # doesn't exist yet at that point -- but autogenerate's raw output
    # then silently omits the constraint entirely rather than adding it
    # back via ALTER TABLE once `orders` exists. Verified this the hard
    # way: the unedited autogenerated script "succeeded" with no error
    # and left resulting_order_id with NO foreign key in the database at
    # all. Fixed by adding it explicitly via op.create_foreign_key once
    # both tables exist; downgrade() drops it first, symmetrically.
    op.create_table('live_batch_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('authorized_by', sa.String(length=128), nullable=False),
    sa.Column('max_intents', sa.Integer(), nullable=False),
    sa.Column('max_notional_per_intent', sa.Float(), nullable=False),
    sa.Column('intents_used', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('intents_used >= 0 AND intents_used <= max_intents', name='ck_live_batch_authorizations_intents_used'),
    sa.CheckConstraint('max_intents > 0', name='ck_live_batch_authorizations_max_intents'),
    sa.CheckConstraint('max_notional_per_intent > 0', name='ck_live_batch_authorizations_max_notional'),
    sa.CheckConstraint('window_end > window_start', name='ck_live_batch_authorizations_window_order'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_batch_authorizations_strategy_id'), 'live_batch_authorizations', ['strategy_id'], unique=False)
    op.create_table('live_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', name='uq_live_positions_strategy_id')
    )
    op.create_index(op.f('ix_live_positions_strategy_id'), 'live_positions', ['strategy_id'], unique=False)
    op.create_table('live_trading_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('broker_name', sa.String(length=32), nullable=False),
    sa.Column('builtin_strategy', sa.String(length=32), nullable=False),
    sa.Column('sma_window', sa.Integer(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('position_size_pct', sa.Float(), nullable=False),
    sa.Column('intent_expiry_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_signal_type', sa.String(length=8), nullable=True),
    sa.Column('last_signal_reference_price', sa.Float(), nullable=True),
    sa.Column('last_signal_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tick_cursor', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("builtin_strategy IN ('always_long','sma_crossover')", name='ck_live_trading_subscriptions_builtin_strategy'),
    sa.CheckConstraint("last_signal_type IS NULL OR last_signal_type IN ('BUY','SELL')", name='ck_live_trading_subscriptions_last_signal_type'),
    sa.CheckConstraint('intent_expiry_seconds > 0 AND intent_expiry_seconds <= 300', name='ck_live_trading_subscriptions_intent_expiry_seconds'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'symbol', name='uq_live_trading_subscriptions_strategy_symbol')
    )
    op.create_index(op.f('ix_live_trading_subscriptions_strategy_id'), 'live_trading_subscriptions', ['strategy_id'], unique=False)
    op.create_table('live_order_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('intent_type', sa.String(length=8), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resulting_order_id', sa.UUID(), nullable=True),
    sa.Column('batch_authorization_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("intent_type IN ('entry','exit','stop')", name='ck_live_order_intents_intent_type'),
    sa.CheckConstraint("side IN ('buy','sell')", name='ck_live_order_intents_side'),
    sa.CheckConstraint("status IN ('pending_approval','approved','rejected','expired','submitted','failed')", name='ck_live_order_intents_status'),
    sa.ForeignKeyConstraint(['batch_authorization_id'], ['live_batch_authorizations.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_order_intents_batch_authorization_id'), 'live_order_intents', ['batch_authorization_id'], unique=False)
    op.create_index(op.f('ix_live_order_intents_strategy_id'), 'live_order_intents', ['strategy_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('live_order_intent_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(length=32), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("side IN ('buy','sell')", name='ck_orders_side'),
    sa.CheckConstraint("status IN ('submitted','failed')", name='ck_orders_status'),
    sa.ForeignKeyConstraint(['live_order_intent_id'], ['live_order_intents.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_live_order_intent_id'), 'orders', ['live_order_intent_id'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_foreign_key(
        'fk_live_order_intents_resulting_order_id_orders',
        'live_order_intents', 'orders', ['resulting_order_id'], ['id'],
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("side IN ('buy','sell')", name='ck_trades_side'),
    sa.CheckConstraint("status IN ('pending_confirmation','failed')", name='ck_trades_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_constraint(
        'fk_live_order_intents_resulting_order_id_orders', 'live_order_intents', type_='foreignkey'
    )
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_live_order_intent_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_live_order_intents_strategy_id'), table_name='live_order_intents')
    op.drop_index(op.f('ix_live_order_intents_batch_authorization_id'), table_name='live_order_intents')
    op.drop_table('live_order_intents')
    op.drop_index(op.f('ix_live_trading_subscriptions_strategy_id'), table_name='live_trading_subscriptions')
    op.drop_table('live_trading_subscriptions')
    op.drop_index(op.f('ix_live_positions_strategy_id'), table_name='live_positions')
    op.drop_table('live_positions')
    op.drop_index(op.f('ix_live_batch_authorizations_strategy_id'), table_name='live_batch_authorizations')
    op.drop_table('live_batch_authorizations')
    # ### end Alembic commands ###
