"""paper trading engine tables

Revision ID: afb82b5073aa
Revises: e303b20de381
Create Date: 2026-09-16 10:00:02.178051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb82b5073aa'
down_revision: Union[str, None] = 'e303b20de381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trading_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('builtin_strategy', sa.String(length=32), nullable=False),
    sa.Column('sma_window', sa.Integer(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('position_size_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tick_cursor', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("builtin_strategy IN ('always_long','sma_crossover')", name='ck_paper_trading_subscriptions_builtin_strategy'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trading_subscriptions_strategy_version_id'), 'paper_trading_subscriptions', ['strategy_version_id'], unique=False)
    op.create_table('daily_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('signal_type', sa.String(length=8), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("signal_type IN ('BUY','SELL')", name='ck_daily_signals_signal_type'),
    sa.ForeignKeyConstraint(['subscription_id'], ['paper_trading_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_signals_subscription_id'), 'daily_signals', ['subscription_id'], unique=False)
    op.create_table('paper_fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_group_id', sa.UUID(), nullable=False),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('fully_filled', sa.Boolean(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("side IN ('buy','sell')", name='ck_paper_fills_side'),
    sa.ForeignKeyConstraint(['subscription_id'], ['paper_trading_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_fills_order_group_id'), 'paper_fills', ['order_group_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_subscription_id'), 'paper_fills', ['subscription_id'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['paper_trading_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', name='uq_paper_positions_subscription_id')
    )
    op.create_index(op.f('ix_paper_positions_subscription_id'), 'paper_positions', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_positions_subscription_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_paper_fills_subscription_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_order_group_id'), table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_index(op.f('ix_daily_signals_subscription_id'), table_name='daily_signals')
    op.drop_table('daily_signals')
    op.drop_index(op.f('ix_paper_trading_subscriptions_strategy_version_id'), table_name='paper_trading_subscriptions')
    op.drop_table('paper_trading_subscriptions')
    # ### end Alembic commands ###
