"""strategy pipeline tables

Revision ID: bda4770d5a76
Revises: edafde39e712
Create Date: 2026-09-16 05:36:58.050369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda4770d5a76'
down_revision: Union[str, None] = 'edafde39e712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('instrument_class', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("instrument_class IN ('equity','options')", name='ck_strategies_instrument_class'),
    sa.CheckConstraint("status IN ('Ideation','Coding','Backtesting','PaperTrading','LiveEligible','Live','Deprecated')", name='ck_strategies_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('static_validation_passed', sa.Boolean(), nullable=False),
    sa.Column('static_validation_errors', sa.JSON(), nullable=True),
    sa.Column('sandbox_passed', sa.Boolean(), nullable=True),
    sa.Column('sandbox_result', sa.JSON(), nullable=True),
    sa.Column('options_legs', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version_number', name='uq_strategy_version_number')
    )
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('strategy_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('base_version_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('ai_verdict', sa.JSON(), nullable=True),
    sa.Column('regenerated_version_id', sa.UUID(), nullable=True),
    sa.Column('regeneration_diff', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','reviewed','regenerated','dismissed')", name='ck_strategy_suggestions_status'),
    sa.ForeignKeyConstraint(['base_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['regenerated_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_suggestions_strategy_id'), 'strategy_suggestions', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_suggestions_strategy_id'), table_name='strategy_suggestions')
    op.drop_table('strategy_suggestions')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_table('strategies')
    # ### end Alembic commands ###
