"""phase24_portfolio_recommendations

Revision ID: c7f60e9797b1
Revises: d4be5e164aba
Create Date: 2026-09-25 12:53:56.563572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f60e9797b1'
down_revision: Union[str, None] = 'd4be5e164aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('allocations', sa.JSON(), nullable=False),
    sa.Column('based_on', sa.JSON(), nullable=False),
    sa.Column('llm_source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='portfolio_recommendation_status'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_recommendations')
    # ### end Alembic commands ###

    # Autogenerate's drop_table() above doesn't drop the native Postgres
    # enum type it implicitly created -- without this, a downgrade+upgrade
    # cycle fails with "type already exists" (same gap noted in every
    # other native-enum migration in this codebase, e.g.
    # 96fec4d5877a_orchestration_engine_tables.py).
    bind = op.get_bind()
    sa.Enum(name='portfolio_recommendation_status').drop(bind, checkfirst=True)
