"""audit log hash chain

Revision ID: ce1b6bee5a66
Revises: 0629b6f53022
Create Date: 2026-09-17 06:30:00.000000

Hand-written, not autogenerated: this table (`audit_log`) already carries
rows from every prior phase (Phase 1's Agent Gateway apply/reject events,
Phase 8's Shadow Mode runs, Phase 9's live trading actions), so the new
`sequence`/`previous_hash`/`hash` columns can't just be added NOT NULL --
existing rows need a real backfill, computed with the exact same
`compute_entry_hash` function `src.audit.service.write_audit_entry` uses
for every new row, so the chain is genuinely continuous from row one, not
just from whenever this migration happened to run.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from src.audit.chain import GENESIS_HASH, compute_entry_hash
from src.models.audit_log import CREATE_AUDIT_LOG_TRIGGER_FUNCTION_SQL, CREATE_AUDIT_LOG_TRIGGER_SQL

# revision identifiers, used by Alembic.
revision: str = "ce1b6bee5a66"
down_revision: Union[str, None] = "0629b6f53022"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("audit_log", sa.Column("sequence", sa.BigInteger(), nullable=True))
    op.add_column("audit_log", sa.Column("previous_hash", sa.String(length=64), nullable=True))
    op.add_column("audit_log", sa.Column("hash", sa.String(length=64), nullable=True))
    op.add_column("audit_log", sa.Column("correlation_id", sa.String(length=64), nullable=True))

    connection = op.get_bind()
    existing_rows = connection.execute(
        sa.text(
            "SELECT id, actor, action, entity_type, entity_id, details, created_at "
            "FROM audit_log ORDER BY created_at ASC, id ASC"
        )
    ).fetchall()

    previous_hash = GENESIS_HASH
    for sequence, row in enumerate(existing_rows, start=1):
        entry_hash = compute_entry_hash(
            sequence=sequence,
            previous_hash=previous_hash,
            actor=row.actor,
            action=row.action,
            entity_type=row.entity_type,
            entity_id=row.entity_id,
            details=row.details,
            created_at=row.created_at,
        )
        connection.execute(
            sa.text(
                "UPDATE audit_log SET sequence = :sequence, previous_hash = :previous_hash, "
                "hash = :hash WHERE id = :id"
            ),
            {
                "sequence": sequence,
                "previous_hash": previous_hash,
                "hash": entry_hash,
                "id": row.id,
            },
        )
        previous_hash = entry_hash

    op.alter_column("audit_log", "sequence", nullable=False)
    op.alter_column("audit_log", "previous_hash", nullable=False)
    op.alter_column("audit_log", "hash", nullable=False)

    op.create_unique_constraint("uq_audit_log_sequence", "audit_log", ["sequence"])
    op.create_index("ix_audit_log_sequence", "audit_log", ["sequence"])
    op.create_index("ix_audit_log_correlation_id", "audit_log", ["correlation_id"])

    # The DB-level append-only enforcement (Build Spec §19): no UPDATE or
    # DELETE against audit_log can ever succeed, regardless of role or
    # code path, short of a superuser first dropping this trigger. Same
    # SQL src/models/audit_log.py's `after_create` event listener uses
    # against a test DB built via `Base.metadata.create_all` -- see that
    # module's comment for why both paths share these two constants.
    op.execute(CREATE_AUDIT_LOG_TRIGGER_FUNCTION_SQL)
    op.execute(CREATE_AUDIT_LOG_TRIGGER_SQL)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log;")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_log_mutation();")
    op.drop_index("ix_audit_log_correlation_id", table_name="audit_log")
    op.drop_index("ix_audit_log_sequence", table_name="audit_log")
    op.drop_constraint("uq_audit_log_sequence", "audit_log", type_="unique")
    op.drop_column("audit_log", "correlation_id")
    op.drop_column("audit_log", "hash")
    op.drop_column("audit_log", "previous_hash")
    op.drop_column("audit_log", "sequence")
