"""phase22_scheduled_job_runs

Revision ID: d4be5e164aba
Revises: e338be4665d1
Create Date: 2026-09-24 17:46:24.031340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4be5e164aba'
down_revision: Union[str, None] = 'e338be4665d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheduler', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('scheduled_run_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', name='scheduled_job_run_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_job_runs_scheduler_job', 'scheduled_job_runs', ['scheduler', 'job_id', 'scheduled_run_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_job_runs_scheduler_job', table_name='scheduled_job_runs')
    op.drop_table('scheduled_job_runs')
    # ### end Alembic commands ###

    # Autogenerate's drop_table() above doesn't drop the native Postgres
    # enum type it implicitly created (same gap noted in
    # 96fec4d5877a_orchestration_engine_tables.py) -- without this, a
    # downgrade+upgrade cycle fails with "type already exists".
    bind = op.get_bind()
    sa.Enum(name='scheduled_job_run_status').drop(bind, checkfirst=True)
