"""agent gateway tables

Revision ID: d73dbd767857
Revises: ac9c1786b12b
Create Date: 2026-09-15 12:15:08.437405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73dbd767857'
down_revision: Union[str, None] = 'ac9c1786b12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_config_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('active', 'rejected', name='config_version_status'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('parsed_config', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_identities',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.String(length=32), nullable=True),
    sa.Column('voice', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('agent_to_agent_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_agent', sa.String(length=64), nullable=False),
    sa.Column('to_agent', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_to_agent_policy_from_agent'), 'agent_to_agent_policy', ['from_agent'], unique=False)
    op.create_index(op.f('ix_agent_to_agent_policy_to_agent'), 'agent_to_agent_policy', ['to_agent'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_identities.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_bindings')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_to_agent_policy_to_agent'), table_name='agent_to_agent_policy')
    op.drop_index(op.f('ix_agent_to_agent_policy_from_agent'), table_name='agent_to_agent_policy')
    op.drop_table('agent_to_agent_policy')
    op.drop_table('agent_identities')
    op.drop_table('agent_config_versions')
    # ### end Alembic commands ###
    # Autogenerate's drop_table doesn't drop the native Postgres enum type it
    # created as a side effect of the column — see the identical fix in the
    # baseline migration's downgrade() for why this is needed.
    sa.Enum(name='config_version_status').drop(op.get_bind(), checkfirst=True)
