"""risk and safety layer tables

Revision ID: e303b20de381
Revises: 56d0bc776443
Create Date: 2026-09-16 08:41:30.997337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e303b20de381'
down_revision: Union[str, None] = '56d0bc776443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switch_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('tripped', sa.Boolean(), nullable=False),
    sa.Column('trip_reason', sa.Text(), nullable=True),
    sa.Column('tripped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('threshold_pct', sa.Float(), nullable=False),
    sa.Column('reset_by', sa.String(length=128), nullable=True),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mode IN ('live','paper')", name='ck_kill_switch_states_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mode', name='uq_kill_switch_states_mode')
    )
    op.create_table('risk_limit_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('limit_name', sa.String(length=64), nullable=False),
    sa.Column('proposed_value', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('staged_by', sa.String(length=128), nullable=False),
    sa.Column('staged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.String(length=128), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('staged','confirmed','applied','rejected')", name='ck_risk_limit_change_requests_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_risk_limits_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_limits')
    op.drop_table('risk_limit_change_requests')
    op.drop_table('kill_switch_states')
    # ### end Alembic commands ###
