"""prompt versioning and heartbeat tables

Revision ID: edafde39e712
Revises: 96fec4d5877a
Create Date: 2026-09-15 19:10:52.177602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edafde39e712'
down_revision: Union[str, None] = '96fec4d5877a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeat_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ok', 'alert', name='heartbeat_status'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_identities.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeat_logs_agent_id'), 'heartbeat_logs', ['agent_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'superseded', name='prompt_version_status'), nullable=False),
    sa.Column('diff_from_previous', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_identities.agent_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version_number', name='uq_prompt_version_agent_number')
    )
    op.create_index(op.f('ix_prompt_versions_agent_id'), 'prompt_versions', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_versions_agent_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_heartbeat_logs_agent_id'), table_name='heartbeat_logs')
    op.drop_table('heartbeat_logs')
    # ### end Alembic commands ###
    # Autogenerate never drops native Postgres enum types -- do it by hand
    # or `upgrade head` after this downgrade recreates the table with a
    # type that already exists.
    sa.Enum(name='prompt_version_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='heartbeat_status').drop(op.get_bind(), checkfirst=True)
